# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fscli < Formula
  desc "A cli tool for firestore"
  homepage "https://github.com/maruware/fscli"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maruware/fscli/releases/download/v0.13.0/fscli_0.13.0_darwin_amd64.tar.gz"
      sha256 "63d4b59fd99bf40efa6f0072bd2fa35478af401b7bdbb66eab114ae72587a384"

      define_method(:install) do
        bin.install "fscli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maruware/fscli/releases/download/v0.13.0/fscli_0.13.0_darwin_arm64.tar.gz"
      sha256 "f76b7830105331a3ae54d0ab27471ce7a49dfc2ba68f5bda2f278aea6e0691b0"

      define_method(:install) do
        bin.install "fscli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maruware/fscli/releases/download/v0.13.0/fscli_0.13.0_linux_amd64.tar.gz"
      sha256 "e048cd0cecf92ab2c259008ec0750ca464a46c109b446441626d1c70c1f827fb"
      define_method(:install) do
        bin.install "fscli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maruware/fscli/releases/download/v0.13.0/fscli_0.13.0_linux_arm64.tar.gz"
      sha256 "bfd62ac95bfcc896b89c122f9488ecd7faa8ed2c7d13b05abd06dfe3b2d635fa"
      define_method(:install) do
        bin.install "fscli"
      end
    end
  end
end
