# This file was generated by GoReleaser. DO NOT EDIT.
cask "fscli" do
  name "fscli"
  desc "A cli tool for firestore"
  homepage "https://github.com/maruware/fscli"
  version "0.13.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fscli"

  on_macos do
    on_intel do
      url "https://github.com/maruware/fscli/releases/download/v#{version}/fscli_#{version}_darwin_amd64.tar.gz"
      sha256 "aa8997416b79970298162ed87f6fa6eef9ae764b988baf33a949e8fc4174dfba"
    end
    on_arm do
      url "https://github.com/maruware/fscli/releases/download/v#{version}/fscli_#{version}_darwin_arm64.tar.gz"
      sha256 "293fa9321999c16d3f7a86cdae51b435bbe5f712d0d8dc3339d582dca403917a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/maruware/fscli/releases/download/v#{version}/fscli_#{version}_linux_amd64.tar.gz"
      sha256 "d6c6e9033ee6f10170429e00ca7b2a108967616edb3bca3a1151bf7dfaaf9844"
    end
    on_arm do
      url "https://github.com/maruware/fscli/releases/download/v#{version}/fscli_#{version}_linux_arm64.tar.gz"
      sha256 "36840cc727547856da03ce06b4bd65c4b86c78e5b3acc75df2c06eb1236a4639"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fscli"]
    end
  end

  # No zap stanza required
end
