# This file was generated by GoReleaser. DO NOT EDIT.
cask "fscli" do
  version "0.15.0"

  on_macos do
    on_intel do
      sha256 "79801d014dfd04ff4558ac2a4c6cbc244704568fb7308e63bfb98e96b132835d"
      url "https://github.com/maruware/fscli/releases/download/v#{version}/fscli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c9283108854d42f7d4506c0936b512a8e99d432714a25be2825d80cdc3f4fd3b"
      url "https://github.com/maruware/fscli/releases/download/v#{version}/fscli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99074a1b7d1cd3f23b2e5cc3b97532c4b2385b5efceef64d905f924e96111a50"
      url "https://github.com/maruware/fscli/releases/download/v#{version}/fscli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf9d77bf162c8e6ce621f106348891ab81b5ee5cb0089aa0943a09d59e952092"
      url "https://github.com/maruware/fscli/releases/download/v#{version}/fscli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fscli"
  desc "A cli tool for firestore"
  homepage "https://github.com/maruware/fscli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fscli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fscli"]
    end
  end

  # No zap stanza required

end
