# This file was generated by GoReleaser. DO NOT EDIT.
cask "fscli" do
  name "fscli"
  desc "A cli tool for firestore"
  homepage "https://github.com/maruware/fscli"
  version "0.14.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fscli"

  on_macos do
    on_intel do
      url "https://github.com/maruware/fscli/releases/download/v#{version}/fscli_#{version}_darwin_amd64.tar.gz"
      sha256 "c8631a123adec5a6cb8c62ce9dd50dc3a4a489cdcd8f8847c2dd12bb51da4802"
    end
    on_arm do
      url "https://github.com/maruware/fscli/releases/download/v#{version}/fscli_#{version}_darwin_arm64.tar.gz"
      sha256 "9ff3282bf21ef4d3636a731f8e6d8b9989d1c2afbb98b85d8dbda2dad9d68bf4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/maruware/fscli/releases/download/v#{version}/fscli_#{version}_linux_amd64.tar.gz"
      sha256 "c26196a97800b6962f747fb24fcdf38c1f0d276d04dea6d8f8e3804e8b845104"
    end
    on_arm do
      url "https://github.com/maruware/fscli/releases/download/v#{version}/fscli_#{version}_linux_arm64.tar.gz"
      sha256 "2bae04f75c3db41a7e431933f7581fb981bd5ea09ac10a8d3663d8b75c4466a0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fscli"]
    end
  end

  # No zap stanza required
end
